# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: make gallery html
      run: |
        cd tool
        python3 make_gallery.py
    - name: image resize
      run: |
        #cd tool
        #python3 resize.py
    - name: Commit files
      run: |
        git config --local user.email "g4.fine.yamanashi@gmail.com"
        git config --local user.name "ishigen425"
        git add .
        git commit -m "make gallery" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
